config/routes.rb
Rails.application.routes.draw do


  # ユーザー認証関係
  devise_scope :user do
    root to: 'homes#top'
    # ゲストログインに関する記述
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # コントローラとアクションは後で確認する
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 管理者側
  namespace :admin do
    delete "posts/destroy_all"
    get '/search', to: 'searches#search'
    resources :users, only:[:index, :show, :edit, :update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only:[:index, :show, :destroy]
    resources :post_comments, only:[:index, :destroy]
  end

  # ユーザー側
  scope module: :public do
    delete 'posts/destroy_all' => 'posts#destroy_all', as: 'destroy_all_posts'
    get 'posts/destroy' => 'posts#destroy_posts' , as: 'destroy_posts'
    resources :posts, only: [:new, :create, :index, :destroy, :show] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :update, :destroy, :index] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
        get :following, :followers, :users_posts
      end
      collection do
        # ユーザーの退会確認画面
        get :unsubscribe
        # ユーザーの退会処理(ステータス更新)
        patch :withdraw
        get "/:id/following_posts/" => "users#following_posts", as: 'following_posts'
      end
    end
    get '/search', to: 'searches#search'
    resources :chats, only: [:show, :create]
  end
  end

# 整理完了

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :caption, presence: true

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }

  def save_tags(savepost_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?

    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name: new_name)
      self.tags << post_tag
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_post_image(width, height)
    post_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(caption: content)
    elsif method == 'partial'
      Post.where('caption LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:latest]
      @posts = Post.latest.page(params[:page])
    elsif params[:old]
      @posts = Post.old.page(params[:page])
    else
      @posts = Post.page(params[:page]).order(created_at: :desc)
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:alert] = "投稿が削除されました"
    redirect_to admin_user_path(post.user)
  end

  def destroy_all
    posts = Post.where(user_id: params[:id])
    posts.destroy_all
    flash[:alert] = "投稿が全て削除されました"
    redirect_to request.referer
  end

  private

  def post_params
    params.require(:post).permit(:caption, :post_image)
  end
end

# 整理完了

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_index.html.erb
<% posts.each do |post| %>
  <div class="row mt-4">
    <div class="col-3"></div>

    <div class="col-1">
      <%= link_to admin_user_path(post.user) do %>
        <%= image_tag post.user.get_profile_image(50, 50) %>
      <% end %>
    </div>

    <div class='col-1'>
      <%= post.user.user_name %>
    </div>

    <div class='col-2'>
      <% post.tags.each do |tag| %>
        <%= link_to admin_search_path(content: tag.name, model: "tag", method: "perfect"), class: "btn btn-outline-dark" do %>
          <%= tag.name %>
        <% end %>
      <% end %>
    </div>

    <div class='col-3'>
      <span><%= link_to "投稿詳細", admin_post_path(post), class: "btn btn-secondary", 'data-turbolinks': false %></span>
      <span class="pl-3"><%= link_to "投稿削除", admin_post_path(post), method: :delete, class: "btn btn-danger" %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class='col-2'>
      <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class='col-7'>
      <%= post.caption %>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class='col-7'>
      <% if post.post_image.attached? %>
        <%= image_tag post.get_post_image(400, 400) %>
      <% else %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class="col-3">
      ♥<%= post.favorites.count %>
      <span class="ml-1">コメント数：<%= post.post_comments.count %></span>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class="col-6 block-line"></div>
  </div>
<% end %>

<!--整理完了-->

app/views/admin/posts/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-2"></div>
    <h3 class="text-under-line">投稿リスト</h3>
  </div>

  <% if @posts.present? %>
    <div class="row mt-3">
      <div class="col-2"></div>
      <div class="col-3 btn-group">
        <%= link_to "投稿新着順", admin_posts_path(latest: "true"), class: "btn btn-outline-primary" %>
        <%= link_to "投稿古い順", admin_posts_path(old: "true"), class: "btn btn-outline-primary" %>
      </div>
    </div>

    <%= render "admin/posts/index", posts: @posts %>

  <% else %>
    <div class="row mt-4">
      <div class="col-3"></div>
      <div class="col-6 text-center">
        <h5>
          <span class="text-under-line-blue">
            投稿はありません
          </span>
        </h5>
      </div>
    </div>
  <% end %>

  <%= render "public/shared/paginate", obj: @posts %>
</div>

<!--整理完了-->

app/views/admin/posts/show.html.erb
<div class="container mt-5">
  <div class="row mt-4">
    <div class="col-2"></div>
    <h3>
      <span class="text-under-line">
        投稿詳細
      </span>
    </h3>
  </div>

  <div class="row mt-4">
    <div class="col-2"></div>

    <div class="col-1">
      <%= link_to admin_user_path(@post.user) do %>
        <%= image_tag @post.user.get_profile_image(50, 50) %>
      <% end %>
    </div>

    <div class='col-1'>
      <%= @post.user.user_name %>
    </div>

    <div class='col-2'>
      <% @post.tags.each do |tag| %>
        <%= link_to search_path(content: tag.name, model: "tag", method: "perfect"), class: "btn btn-outline-dark" do %>
          <%= tag.name %>
        <% end %>
      <% end %>
    </div>

    <div class='col-2'>
      <%= link_to "投稿削除", admin_post_path(@post), method: :delete, class: "btn btn-danger" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class='col-2'>
      <%= @post.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class='col-7'>
      <%= @post.caption %>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class='col-7'>
      <% if @post.post_image.attached? %>
        <%= image_tag @post.get_post_image(600, 600) %>
      <% else %>
      <% end %>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-3"></div>
    <div class="col-3">
      ♥<%= @post.favorites.count %> いいね
      <span class="ml-1">コメント件数：<%= @post.post_comments.count %></span>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-3"></div>
    <div class="col">
      <% @post.post_comments.each do |post_comment| %>
        <table>
          <tr>
            <td>
              <%= link_to admin_user_path(post_comment.user) do %>
                <%= image_tag post_comment.user.get_profile_image(50, 50) %>
              <% end %>
              <%= post_comment.user.user_name %>
            </td>
          </tr>

          <tr>
            <td><%= post_comment.comment %></td>
            <td class="pl-3">
              <%= link_to "コメント削除", admin_post_comment_path(post_comment), method: :delete, class: "btn btn-danger btn-sm" %>
            </td>
          </tr>

          <tr>
            <td><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

<!--整理完了-->