config/routes.rb
Rails.application.routes.draw do


  # ユーザー認証関係
  devise_scope :user do
    root to: 'homes#top'
    # ゲストログインに関する記述
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # コントローラとアクションは後で確認する
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 管理者側
  namespace :admin do
    delete "posts/destroy_all"
    get '/search', to: 'searches#search'
    resources :users, only:[:index, :show, :edit, :update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only:[:index, :show, :destroy]
    resources :post_comments, only:[:index, :destroy]
  end

  # ユーザー側
  scope module: :public do
    delete 'posts/destroy_all' => 'posts#destroy_all', as: 'destroy_all_posts'
    get 'posts/destroy' => 'posts#destroy_posts' , as: 'destroy_posts'
    resources :posts, only: [:new, :create, :index, :destroy, :show] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :update, :destroy, :index] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
        get :following, :followers, :users_posts
      end
      collection do
        # ユーザーの退会確認画面
        get :unsubscribe
        # ユーザーの退会処理(ステータス更新)
        patch :withdraw
        get "/:id/following_posts/" => "users#following_posts", as: 'following_posts'
      end
    end
    get '/search', to: 'searches#search'
    resources :chats, only: [:show, :create]
  end
  end

# 整理完了

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :user_rooms
  has_many :chats


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :user_name, presence: true

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # 検索機能の記述
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(user_name: content)
    elsif method == 'partial'
      User.where('user_name LIKE ?', '%' + content + '%')
    end
  end

  # ゲストログインに関する記述
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.user_name = "guestuser"
      user.last_name = 'ゲスト'
      user.first_name = '太郎'
      user.last_name_kana = 'ゲスト'
      user.first_name_kana = 'タロウ'
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.page(params[:page]).per(5).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集が完了しました"
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :user_name,
      :email,
      :introduction,
      :is_active
    )
  end
end

# 整理完了

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<table class="table mt-3 text-center">
  <tr>
    <th class="col-1"></th>
    <th class="col-2">ユーザー名</th>
    <th class="col-1">投稿数</th>
    <th class="col-2">フォロー数</th>
    <th class="col-2">フォロワー数</th>
    <th class="col-2">会員ステータス</th>
    <th class="col-2"></th>
  </tr>

  <% users.each do |user| %>
    <tr>
      <td class="col-1">
        <%= link_to admin_user_path(user) do %>
          <%= image_tag user.get_profile_image(50, 50) %>
        <% end %>
      </td>
      <td class="col-2"><%= user.user_name %></td>
      <td class="col-1">投稿数: <%= user.posts.count %></td>
      <td class="col-2">フォロー数: <%= user.followings.count %></td>
      <td class="col-2">フォロワー数: <%= user.followers.count %></td>
      <td class="col-2">
        <% if user.is_active == true %>
          <span style="color: #1a8066;">会員</span>
        <% else %>
          <span class="text-danger">退会済</span>
        <% end %>
      </td>
      <td class="col-2">
        <%= link_to "ユーザー詳細", admin_user_path(user), class: "btn btn-secondary", 'data-turbolinks': false %>
      </td>
    </tr>
  <% end %>
</table>

<!--整理完了-->

app/views/admin/users/edit.html.erb
<div class="container mt-5">
  <div class="row main-row">
    <div class="col-12">
      <div class="form-row">
        <h4 class="form-group col-4">
          <span class="text-under-line">
            <%= @user.last_name + @user.first_name %>さんの会員情報編集
          </span>
        </h4>
      </div>

      <%= form_with model: @user, url: admin_user_path do |f| %>

        <%= render "layouts/errors", obj: @user %>

        <div class="form-row mt-3">
          <span class="form-group col-3"><%= f.label :会員id %></span>
          <div class="form-group col-3">
            <%= @user.id %>
          </div>
        </div>

        <div class="form-row">
          <span class="form-group col-3 pt-4">名前</span>
          <div class="form-group col-3">
            <label for="last_name">(姓)</label>
            <%= f.text_field :last_name, class: "form-control" %>
          </div>
          <div class="form-group col-3">
            <label for="first_name">(名)</label>
            <%= f.text_field :first_name, class: "form-control" %>
          </div>
        </div>

        <div class="form-row">
          <span class="form-group col-3 pt-4">フリガナ</span>
          <div class="form-group col-3">
            <label for="last_name_kana">(セイ)</label>
            <%= f.text_field :last_name_kana, class: "form-control" %>
          </div>
          <div class="form-group col-md-3">
            <label for="first_name_kana">(メイ)</label>
            <%= f.text_field :first_name_kana, class: "form-control" %>
          </div>
        </div>

        <div class="form-row">
          <span class="form-group col-3">ユーザー名</span>
          <div class="form-group col-3">
            <%= f.text_field :user_name, class: "form-control" %>
          </div>
        </div>

        <div class="form-row">
          <span class="form-group col-3"><%= f.label :自己紹介文 %></span>
          <div class="form-group col-6">
            <%= f.text_area :introduction, class: "form-control", rows: 4 %>
          </div>
        </div>

         <div class="form-row">
          <span class="form-group col-3">メールアドレス</span>
          <div class="form-group col-6">
            <%= f.text_field :email, class: "form-control" %>
          </div>
        </div>

        <div class="form-row">
          <span class="form-group col-3">パスワード(6文字以上)</span>
          <div class="form-group col-3">
            <%= f.password_field :password, class: "form-control" %>
          </div>
        </div>

        <div class="form-row">
          <span class="form-group col-3">パスワード(確認用)</span>
          <div class="form-group col-3">
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
        </div>

        <div class="form-row">
          <span class="form-group col-3"><%= f.label :会員ステータス %></span>
          <div class="form-group col-3">
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active_true, "有効" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active_false, "退会" %>
          </div>
        </div>

        <div class="actions form-group justify-content:center; d-flex">
          <span class="form-group col-3"></span>
          <%= f.submit "変更内容を保存", class: "btn btn-success col-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!--整理完了-->

app/views/admin/users/index.html.erb
<div class="container mt-5">
  <h3>
    <span class="text-under-line">
      ユーザーリスト(管理者側)
    </span>
  </h3>

  <% if @users.present? %>
    <%= render "admin/users/index", users: @users %>
  <% else %>
    <div class="row mt-4">
      <div class="col-3">
      </div>
      <div class="col-6 text-center">
        <h5>
          <span class="text-under-line-blue">
            ユーザーはいません
          </span>
        </h5>
      </div>
    </div>
  <% end %>

</div>

<%= render "public/shared/paginate", obj: @users %>

<!--整理完了-->

app/views/admin/users/show.html.erb
<div class="container mt-5">

  <div class="row">
    <div class="col-2">
    </div>
    <div class="col-3">
      <%= image_tag @user.get_profile_image(200, 200) %>
    </div>

    <div class="col-6">
      <table class="table mt-3">
        <tr>
          <td><%= @user.user_name %></td>
          <td><%= link_to "プロフィール編集", edit_admin_user_path(@user), class: "btn btn-success" %></td>
        </tr>

        <tr>
          <td><%= @user.last_name %> <%= @user.first_name %></td>
        </tr>

        <tr>
          <td><%= @user.last_name_kana %> <%= @user.first_name %></td>
        </tr>

        <tr>
          <td><%= @user.email %></td>
        </tr>

        <tr>
          <td>投稿<%= @user.posts.count %>件</td>
          <td>
            <%= link_to admin_user_followings_path(@user), class: "btn btn-outline-primary" do %>
              フォロー中<%= @user.followings.count %>人
            <% end %>
            <span class="pl-1">
              <%= link_to admin_user_followers_path(@user), class: "btn btn-outline-primary" do %>
                フォロワー<%= @user.followers.count %>人
              <% end %>
            </span>
          </td>
        </tr>

        <tr>
          <td><%= @user.introduction %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<div class="container mt-5">
  <% if @posts.present? %>
    <div class="row">
      <div class="col-3">
      </div>

      <div class="col-3">
        <%= link_to admin_posts_destroy_all_path(id: @user.id), method: :delete, class: "btn btn-danger", data: { confirm: "本当に全削除しますか？" } do %>
          投稿を全削除
        <% end %>
      </div>
    </div>

    <%= render "admin/posts/index", posts: @posts %>

  <% else %>
    <div class="row mt-4">
      <div class="col-3">
      </div>

      <div class="col-6 text-center">
        <h5>
          <span class="text-under-line-blue">
            <%= @user.user_name %>さんの投稿はありません
          </span>
        </h5>
      </div>
    </div>
  <% end %>
</div>



<%= render "public/shared/paginate", obj: @posts %>

<!--整理完了-->