config/routes.rb
Rails.application.routes.draw do


  # ユーザー認証関係
  devise_scope :user do
    root to: 'homes#top'
    # ゲストログインに関する記述
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # コントローラとアクションは後で確認する
  devise_for :users, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  # 管理者側
  namespace :admin do
    delete "posts/destroy_all"
    get '/search', to: 'searches#search'
    resources :users, only:[:index, :show, :edit, :update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :posts, only:[:index, :show, :destroy]
    resources :post_comments, only:[:index, :destroy]
  end

  # ユーザー側
  scope module: :public do
    delete 'posts/destroy_all' => 'posts#destroy_all', as: 'destroy_all_posts'
    get 'posts/destroy' => 'posts#destroy_posts' , as: 'destroy_posts'
    resources :posts, only: [:new, :create, :index, :destroy, :show] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :update, :destroy, :index] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      member do
        get :favorites
        get :following, :followers, :users_posts
      end
      collection do
        # ユーザーの退会確認画面
        get :unsubscribe
        # ユーザーの退会処理(ステータス更新)
        patch :withdraw
        get "/:id/following_posts/" => "users#following_posts", as: 'following_posts'
      end
    end
    get '/search', to: 'searches#search'
    resources :chats, only: [:show, :create]
  end
  end

# 整理完了

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  validates :caption, presence: true

  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }

  def save_tags(savepost_tags)
    current_tags = self.tags.pluck(:name) unless self.tags.nil?

    old_tags = current_tags - savepost_tags
    new_tags = savepost_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      post_tag = Tag.find_or_create_by(name: new_name)
      self.tags << post_tag
    end
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def get_post_image(width, height)
    post_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(caption: content)
    elsif method == 'partial'
      Post.where('caption LIKE ?', '%' + content + '%')
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

  def self.search_comments_for(content, method)
    if method == 'perfect'
      PostComment.where(comment: content)
    elsif method == 'partial'
      PostComment.where('comment LIKE ?', '%' + content + '%')
    end
  end
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags

  scope :merge_posts, -> (tags) { }

  def self.search_posts_for(content, method)
    if method == 'perfect'
      tags = Tag.where(name: content)
    elsif method == 'partial'
      tags = Tag.where('name LIKE ?', '%' + content + '%')
    end
    return tags.map(&:posts).flatten.sort_by(&:created_at).reverse
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :user_rooms
  has_many :chats


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :user_name, presence: true

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  # 検索機能の記述
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(user_name: content)
    elsif method == 'partial'
      User.where('user_name LIKE ?', '%' + content + '%')
    end
  end

  # ゲストログインに関する記述
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.user_name = "guestuser"
      user.last_name = 'ゲスト'
      user.first_name = '太郎'
      user.last_name_kana = 'ゲスト'
      user.first_name_kana = 'タロウ'
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search

    @model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@records = User.search_for(@content, @method)
		else
			@records = Book.search_for(@content, @method)
		end


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h4 style="color: red;">
      <strong>
      <%= t "errors.template.header",model:t("models.#{obj.model_name}"),count:obj.errors.count %>
      </strong>
    </h4>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li>
          <span class="text-under-line-red">
          <%= message %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <h6>
          &copy;
          <span class="fa-solid fa-bowling-ball"></span>
          Bowlers〜ボウラーと繋がるSNS〜
        </h6>
      </div>
    </div>
  </div>
</footer>

<!--整理完了-->

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark header-bg">
    <div class="container">
      <h3>
        <%= link_to root_path, class: 'nav-link text-light' do %>
          <i class="fa-solid fa-bowling-ball"></i>
          Bowlers
        <% end %>
      </h3>

      <% if user_signed_in? %>
        <span class="nav-link text-light">
          <%= current_user.user_name %> さんがログインしています
        </span>
      <% elsif admin_signed_in? %>
        <span class="nav-link text-light">
          管理者でログインしています
        </span>
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

          <% if user_signed_in? %>

            <li>
              <%= link_to user_path(current_user), class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> マイページ
              <% end %>
            </li>

            <li>
              <%= link_to users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> ユーザーリスト
              <% end %>
            </li>

            <li>
              <%= link_to posts_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-rectangle-list"></i> 投稿リスト
              <% end %>
            </li>

            <li>
              <%= link_to new_post_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-plus"></i> 新規投稿
              <% end %>
            </li>

            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>

          <% elsif admin_signed_in? %>
            <li>
              <%= link_to admin_users_path, class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> ユーザーリスト
              <% end %>
            </li>

            <li>
              <%= link_to admin_posts_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-rectangle-list"></i> 投稿リスト
              <% end %>
            </li>

            <li>
              <%= link_to admin_post_comments_path, class: 'nav-link text-light' do %>
                <i class="fa-solid fa-comment-dots"></i>コメントリスト
              <% end %>
            </li>

            <li>
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
              <% end %>
            </li>

          <% end %>

        </ul>
      </div>
    </div>
  </nav>
</header>

<% flash.each do |message_type, message| %>
  <div class="flash-message <%= message_type %>"><%= message %></div>
<% end %>

<div class="form-row mt-3">
  <div class="col"></div>
  <div class="col-4"><%= render 'public/searches/form' %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Bowlers</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.6.2/css/bootstrap.min.css">
  <!-- これを適用させると画面がおかしくなる -->
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://kit.fontawesome.com/1043f0fa51.js" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.6.7/js/bootstrap.min.js"></script>
</head>

<body>
  <% if user_signed_in? || admin_signed_in? %>
    <%= render 'layouts/header' %>
  <% end %>

  <!-- 元々の記述 -->
  <%= yield %>

  <%= render 'layouts/footer' %>
</body>

</html>

<!--整理完了-->